module.exports = {
  "docs": {
    "Getting Started": [
      "getting_started/install",
      "getting_started/julia_primer",
      "getting_started/tips",
      "getting_started/comparison",
      "getting_started/types",
      "getting_started/other_types",
      "getting_started/datasets"
    ],
    "File I/O": [
      "io/file_import",
      "io/file_write",
      "io/delimited",
      "io/genepop",
      "io/structure",
      "io/vcf",
    ],
    "Working with PopData": [
      "popdata_basics/manipulate",
      "popdata_basics/accessing",
      "popdata_basics/add_info",
      "popdata_basics/exclusion",
      "popdata_basics/conditionals",
      "popdata_basics/populations",
      "popdata_basics/viewdata",
      "popdata_basics/dataexploration",
      "popdata_basics/indexing"
    ],
    "Analyses":[
      "analyses/hardyweinberg",
      "analyses/relatedness",
      "analyses/fstatistics"
    ],
    "Simulations":[
      "simulations/simulate_samples",
      "simulations/breeding_crosses",
      "simulations/sibship_simulations",
    ],    
    "API": [
      "api/api",
      {
        "PopGen":[
          "api/PopGen/dataexploration",
          "api/PopGen/fstmethods",
          "api/PopGen/fstpermutations",
          "api/PopGen/hardyweinberg",
          "api/PopGen/heterozygosity",
          "api/PopGen/pairwisefst",
          "api/PopGen/pairwiserelatedness",
          "api/PopGen/relatednessmoments",
          "api/PopGen/summaryinfo",
          "api/PopGen/utils",
        ]
      },
      {
        "PopGenCore":[
          "api/PopGenCore/allelefreq",
          "api/PopGenCore/conditionals",
          "api/PopGenCore/datasets",
          "api/PopGenCore/delimited",
          "api/PopGenCore/genepop",
          "api/PopGenCore/ioutils",
          "api/PopGenCore/manipulate",
          "api/PopGenCore/permutations",
          "api/PopGenCore/read",
          "api/PopGenCore/structure",
          "api/PopGenCore/types",
          "api/PopGenCore/variantcall",
        ]
      },
      {
      "PopGenSims":[
        "api/PopGenSims/popgensims_cross",
        "api/PopGenSims/popgensims_samples",
        "api/PopGenSims/popgensims_sibship",
        "api/PopGenSims/popgensims_utils",
      ]
      }
    ]
  }
}
