name: pkgtests
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  push:
    branches: 
      - main
    paths-ignore:
      - "docs/**"

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.8'
          - '1.9'
          - '1.10'
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v7
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Setup package environment
        uses: julia-actions/julia-buildpkg@latest
      - name: Package tests
        uses: julia-actions/julia-runtest@latest
